#!/bin/bash
# check

echo "Checking the solution of the challenge"

grep -Fq "http.ListenAndServe" main.go
if [ $? != 0 ]; then
  fail-message "Please make sure you have added the 'ListenAndServe' call to your main.go file"
fi
